version: '3.3'
services:
  chat:
    build: chat
    ports:
    - 6969:6969
    volumes:
    - ./chat:/app:ro
    command: 'php /app/server.php'
  php:
    build: .
    volumes:
    - ./www:/var/www/html/php:ro
    - ./jwt-keys:/opt/jwt-keys:ro
  nginx:
    image: nginx:latest
    ports:
    - 80:80
    volumes:
    - ./nginx/conf.d:/opt/conf.d:ro
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
#    - ./certbot:/etc/letsencrypt:ro # Brukes med ssl
    - ./www:/var/www/html:ro
    - ./logs:/var/log/nginx:rw
